"""empty message

Revision ID: fce2d4e2ca54
Revises: 6d7c51463a2b
Create Date: 2020-04-09 21:24:42.226508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce2d4e2ca54'
down_revision = '6d7c51463a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.drop_column('artist', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('artist', 'seeking_venue')
    # ### end Alembic commands ###
